variables:
  GIT_CLEAN_FLAGS: none

stages:
  - unit_test
  - integration_test_android_emulator
  - integration_test_ios_simulator

unit_test:
  stage: unit_test
  only:
    - merge_request
  script:
    - fvm flutter --version
    - flutter --version
    - fvm flutter test test/ --reporter expanded | sed -E 's/([0-9]{2}:[0-9]{2}) \+([0-9]+): ([^:]+): (.+)/\1 \4/'
    - cd example
    # - fvm flutter test integration_test/hibon_integration_test.dart -d emulator-5554
    # - fvm flutter test integration_test/hibon_integration_test.dart -d F88A2BC9-E730-49D9-9015-8245583D3877